languageCode = "en"
languageName = "English"
weight = 1
title = "Fikiblog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "poker rulet slot i po koji jaci singl"
dateFormat = "2 January 2006"
author = { name = "Fixotron d.o.o", image = "img/avatar.png", headline = "Ovo mi je lepeza majmune" }
logo = "23.png"
