colorScheme = "Noir"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
highlightCurrentMenuArea = true
disableTextInHeader = true
mainSections = [ "posts" ]

[header]
layout = "fixed"

[footer]
showMenu = false
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "posl-min.png"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/blowfish_lowkey/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showViews = true
showLikes = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = true
showWordCount = true
showSummary = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]

[list]
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]
apiKey = "AIzaSyCdsjWJmhLwojm5cuFVSiYqZOkJ7ZPFmFo"
authDomain = "fikiblog-dd61a.firebaseapp.com"
projectId = "fikiblog-dd61a"
storageBucket = "fikiblog-dd61a.firebasestorage.app"
messagingSenderId = "47343882491"
appId = "1:47343882491:web:f679eef9f9ea4572e1a05e"
measurementId = "G-3MFBFXSEFE"

[fathomAnalytics]

[verification]
